[package]
name = "atomic_test"
version = "1.0.0"
authors = ["Théo Hay <priv.theohay@gmail.com>"]
edition = "2018"

[dependencies]
num_cpus = "^1.13.0"
num-format = "^0.4.0"
snmalloc-rs = { version = "0.2.27", features = ["native-cpu"] } 